#Pipeline with docker

trigger:
- main

variables:
  tag: '$(Build.BuildId)'
  Registryname: XXX
  DockerRepository: YYY

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:

    - task: Docker@2
      inputs:
        containerRegistry: 'Registryname'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: $(tag)

- stage: Provision
  displayName: Terraform to provision
  dependsOn: Build
  jobs:
    - job: Provision
      displayName: Provision container
      pool:
        vmimage: ubuntu latest
      variables: 
        -group: TFeVARS
      steps:
      - script:
          terraform init
          terraform plan -input=false
          terraform apply -input=false -auto-approve
        name: terraform
        displayName: run terraform
        env:
          ARM_CLIENT_ID: $(ARM_CLIENT_ID)
          ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
          ARM_TENANT_ID: $(ARM_TENANT_ID)
          ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
          TF_VAR_buildno: $(tag)
